export enum EntityType {
  PRIVATE = 'PRIVATE',
  GOVERNMENT = 'GOVERNMENT',
  PUBLIC = 'PUBLIC',
  PIFRELATED = 'PIF_RELATED',
  INDIVIDUAL = 'INDIVIDUAL',
}

export enum BusinessType {
  SUPPLIER = 'SUPPLIER',
  CONTRACTOR = 'CONTRACTOR',
  CONSULTANT = 'CONSULTANT',
  FFF_OSE = 'FFF_OSE',
  SOLE_TRADER = 'SOLE_TRADER',
}